#ifndef FASTEV_VERSION
#define FASTEV_VERSION

#define _APP_VERSION_MAJOR 1
#define _APP_VERSION_MINOR 0
#define _APP_VERSION_PATCH 8
#define PPCAT_NX(A, B, C) A##.##B##.##C
#define PPCAT(A, B, C) PPCAT_NX(A, B, C)
#define STRINGIZE_NX(A) #A
#define STRINGIZE(A) STRINGIZE_NX(A)
#define _APP_VERSION STRINGIZE(PPCAT(_APP_VERSION_MAJOR, _APP_VERSION_MINOR, _APP_VERSION_PATCH))

#endif
